import type { Metadata } from "next";
import localFont from "next/font/local";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { QueryProvider } from "@/providers/query-provider";
import { SheetProvider } from "@/providers/sheet-provider";
import { Toaster } from "@/components/ui/sonner"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
        <html lang="en">
        
          <body
            className={`antialiased custom-scrollbar`}
          >
            
            <QueryProvider>
              <Toaster />
              <SheetProvider />
              
              {children}
              
            </QueryProvider>
          </body>
      </html>
    </ClerkProvider>
  );
}
